### PR TITLE
Wrong value is set for end_day, end_year, end_month it should be EndBoundary and not StartBoundary

### PR DESCRIPTION
**Pull request by Vasu1105**

### CODE REVIEW

**Comment by djberg96** [comment]
Good catch!

**Comment by djberg96** [comment]
@Vasu1105 Note that I'm not really using this library any more, nor any of the win32 gems, and I feel I'm not doing a great job of maintaining them. Would you or your company be interested in taking over maintenance?

**Comment by btm** [comment]
@djberg96 yes, we can bring them over to Chef and maintain them. If you want to transfer them to me, I'll move them into the github Chef organization. Last I knew that had to be done as two steps if the current owner wasn't a part of the github organization.

**Comment by djberg96** [comment]
@btm, ok, I'll start transferring them over to you. There's a few I'll keep either because they're outdated, experimental, or have effectively already been supplanted by newer gems. I'll start turning over the rest this week.

**Pull request merged**
